name: iOSMemScan
options:
  bundleIdPrefix: com.memscan
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  settingPresets: all
  createIntermediateGroups: true

settings:
  base:
    TARGETED_DEVICE_FAMILY: "1,2"
    STRIP_STYLE: all
    COPY_PHASE_STRIP: true
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  iOSMemScan:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    info:
      path: iOSMemScan/Resources/Info.plist
    entitlements:
      path: iOSMemScan/Resources/Entitlements.plist
      # 不让 Entitlements 加入 Copy Bundle Resources
      destination: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.memscan.ios
        INFOPLIST_FILE: iOSMemScan/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOSMemScan/Resources/Entitlements.plist
        GENERATE_INFOPLIST_FILE: NO
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        ARCHS: arm64
        ONLY_ACTIVE_ARCH: NO
        CLANG_ENABLE_OBJC_ARC: YES
        GCC_OPTIMIZATION_LEVEL: s
        ENABLE_BITCODE: NO
    sources:
      - path: iOSMemScan
        name: iOSMemScan
        type: group
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
          - "build"
          - ".build"
    dependencies:
      - framework: Foundation.framework
      - framework: UIKit.framework
      - framework: CoreFoundation.framework
